# Generated by Django 4.1.3 on 2022-11-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_balance',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
