version: "3.9"

services:
  redis:
    image: redis
    restart: always

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build:
      context: .
    command: python3 manage.py runserver 0.0.0.0:5000
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    env_file:
      - .env.dev
    depends_on:
      - db
  celery:
    build: .
    command: celery -A counter worker -l info
    env_file:
      - .env.dev
    volumes:
      - ./project/:/usr/src/code/
    depends_on:
      - redis
  celery-beats:
    build: .
    command: celery -A counter beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env.dev
    volumes:
      - ./project/:/usr/src/code/
    depends_on:
      - redis

