# Generated by Django 4.1.3 on 2022-11-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sum_of_withdrawing',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
