# Generated by Django 4.1.3 on 2022-11-08 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_sum_of_withdrawing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='sum_of_withdrawing',
        ),
        migrations.AddField(
            model_name='category',
            name='spent_sum',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_of_category',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
