# Generated by Django 4.1.3 on 2022-11-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name_of_category',
            field=models.CharField(max_length=50),
        ),
    ]
