# Generated by Django 4.1.3 on 2022-11-09 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_category_sum_of_withdrawing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='spent_sum',
            field=models.IntegerField(default=0),
        ),
    ]
